### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Denis-Shalaev** [veita/oracle-java-download#2]
```
$ ./get_download_links JDK7
Wait 5 seconds for browser startup...
Exception in thread "main" java.lang.UnsupportedClassVersionError: automation/browser/JdkDownload : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:472)
5d3a585e5f499a41c0f7005b6834557a78d733e1a345644c4256a5120f3a6d4f
```

**Comment by veita** [comment]
The download of JDK7 is not supported since it requires an Oracle account. The download tool itself requires Java 8 or higher to run.
